"""empty message

Revision ID: c952f07c8417
Revises: 
Create Date: 2024-08-21 14:11:43.584428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c952f07c8417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_index('ix_user_username')
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=True))

    with op.batch_alter_table('word_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word1_synonym1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('word1_synonym2', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('word2_synonym1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('word2_synonym2', sa.String(length=100), nullable=False))
        batch_op.alter_column('word1',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('word2',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('used',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text("'False'"))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('used',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text("'False'"))
        batch_op.alter_column('word2',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('word1',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('word2_synonym2')
        batch_op.drop_column('word2_synonym1')
        batch_op.drop_column('word1_synonym2')
        batch_op.drop_column('word1_synonym1')

    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        batch_op.drop_column('used')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')
        op.create_index('ix_user_email', 'user', ['email'], unique=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
