"""Fix foreign key relationships

Revision ID: 2cdc32ccb98c
Revises: 97796fda6da7
Create Date: 2024-10-07 16:09:59.400061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdc32ccb98c'
down_revision = '97796fda6da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_word_pair_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('attempt_word_pair_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('attempt_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_word_pair', ['user_word_pair_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('word_pair_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_pair_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('attempt_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('attempt_word_pair_id_fkey', 'word_pair', ['word_pair_id'], ['id'])
        batch_op.drop_column('user_word_pair_id')

    # ### end Alembic commands ###
