"""Add new columns to UserStats

Revision ID: b87cf2ca588b
Revises: fc5004192e79
Create Date: 2024-10-07 21:41:53.724090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87cf2ca588b'
down_revision = 'fc5004192e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_try_successes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_tries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hints_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_puzzles_played', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_column('total_puzzles_played')
        batch_op.drop_column('hints_used')
        batch_op.drop_column('total_tries')
        batch_op.drop_column('first_try_successes')

    # ### end Alembic commands ###
