"""empty message

Revision ID: c7779b654b7e
Revises: 5269625335f7
Create Date: 2024-09-12 13:49:50.342770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7779b654b7e'
down_revision = '5269625335f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word1_status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('word2_status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        batch_op.drop_column('word2_status')
        batch_op.drop_column('word1_status')

    # ### end Alembic commands ###
