"""empty message

Revision ID: 91afe2e7b5d4
Revises: 
Create Date: 2024-08-26 15:29:55.019179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91afe2e7b5d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('_alembic_tmp_synonym')
    with op.batch_alter_table('synonym', schema=None) as batch_op:
        batch_op.alter_column('synonyms',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_streak', sa.Integer(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_index('ix_user_username')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('max_streak')
        batch_op.drop_column('current_streak')
        batch_op.drop_column('total_points')

    with op.batch_alter_table('synonym', schema=None) as batch_op:
        batch_op.alter_column('synonyms',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=True)

    op.create_table('_alembic_tmp_synonym',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), nullable=False),
    sa.Column('synonyms', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###
