"""Update Guest and WordPair models

Revision ID: 52feb79dd8b6
Revises: b26f98f6b419
Create Date: 2024-10-04 13:41:50.953759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52feb79dd8b6'
down_revision = 'b26f98f6b419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['unique_guest_id'])

    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        batch_op.drop_constraint('user_word_pair_guest_id_fkey', type_='foreignkey')
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_word_pair_guest_id_fkey', 'guest', ['guest_id'], ['id'])

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
