"""Add guest_id to User table and update UserWordPair

Revision ID: 956a9a121d8b
Revises: 8fcc12875236
Create Date: 2024-10-03 16:45:46.502740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956a9a121d8b'
down_revision = '8fcc12875236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), autoincrement=True, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###
