"""make nullable false for guest

Revision ID: b26f98f6b419
Revises: 62eed29675b6
Create Date: 2024-10-03 21:36:33.790831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26f98f6b419'
down_revision = '62eed29675b6'
branch_labels = None
depends_on = None


def upgrade():
    # Step to ensure unique_guest_id is populated
    op.execute("UPDATE guest SET unique_guest_id = 0 WHERE unique_guest_id IS NULL")

    # Now alter the column to NOT NULL
    op.alter_column('guest', 'unique_guest_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('unique_guest_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
