"""Remove attempts column from UserWordPair

Revision ID: d7262b3243a0
Revises: 04a5d5f09ab8
Create Date: 2024-10-07 16:51:16.320163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7262b3243a0'
down_revision = '04a5d5f09ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempt')
    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        batch_op.drop_column('id')
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))

    op.create_table('attempt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word_pair_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word1_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('word1_synonym_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('word2_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('word2_synonym_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='attempt_user_id_fkey'),
    sa.ForeignKeyConstraint(['word_pair_id'], ['word_pair.id'], name='attempt_word_pair_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attempt_pkey')
    )
    # ### end Alembic commands ###
