"""Fix relationships between UserWordPair and Attempt

Revision ID: f0652e6f2682
Revises: 2cdc32ccb98c
Create Date: 2024-10-07 16:24:34.523695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0652e6f2682'
down_revision = '2cdc32ccb98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        # Allow NULLs temporarily
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))

    # Set a default value for existing records
    op.execute('UPDATE user_word_pair SET attempts = 0 WHERE attempts IS NULL')

    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        # Now make the column NOT NULL
        batch_op.alter_column('attempts', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
        batch_op.drop_column('attempts')
    # ### end Alembic commands ###
