"""Renamed guest_id to unique_guest_id in User model

Revision ID: f367b63a0796
Revises: 956a9a121d8b
Create Date: 2024-10-03 16:56:06.871965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f367b63a0796'
down_revision = '956a9a121d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_guest_id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('unique_guest_id')

    # ### end Alembic commands ###
