"""Add attempts from github table

Revision ID: fc5004192e79
Revises: d7262b3243a0
Create Date: 2024-10-07 16:52:58.070680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5004192e79'
down_revision = 'd7262b3243a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
    #   batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=False))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('user_word_pair', schema=None) as batch_op:
    #    batch_op.drop_column('attempts')
    pass
    # ### end Alembic commands ###
